Quiz
Kinggred/Praktyki pull request #7
Opened 2021-06-10 09:37 UTC by Kinggred

Nowa uproszczona wersja

2021-06-10 13:49 UTC, FilipProgrammer commented on quiz/quiz.py
> +class File_load():
Ta klasa jest bezstanowa, można bez problemu przerobić ją na funkcję

2021-06-10 13:55 UTC, Kinggred commented on quiz/quiz.py
> +class File_load():
Poprawiłem

2021-06-10 14:25 UTC, FilipProgrammer requested changes

2021-06-10 14:25 UTC, FilipProgrammer commented on quiz/quiz.py
> +q = File_load().load_json("praktyki/062021/maks_grupinski/repo/quiz/text.json", "rt")
ścieżka może być częściowo budowana przez python'a. Dla programisty będzie to wygodniejsze bo będzie musiał tylko dodać ostatni człon "text.json", który w sumie mógłby się nazywać questions.json

2021-06-10 14:25 UTC, FilipProgrammer commented on quiz/quiz.py
> +while i < len(questions):
w Pythonie w takim przypadku można zrobić konstrukcję:
```
for question in questions:
    ...
```
Działa to dla zmiennych które są Iterable czyli np. listy, tuple, dict's. Eliminuje potrzebę tworzenia zmiennej iteracyjnej i nie martwimy się o odpowiedni warunek iteracyjny.

Jeśli używamy pętli tylko do prostych, jednolinijkowych operacji to możemy się zainteresować takim mechanizmem: https://realpython.com/list-comprehension-python/

2021-06-10 14:25 UTC, FilipProgrammer commented on quiz/quiz.py
> +class Quiz:
Moim zdaniem metody takie jak: question, answers, was_ans_cor można przenieść do klasy Question, są one ściśle ze sobą powiązane. Klasa pytanie powinna móc wyświetlać pytanie, prawidłowe odpowiedzi i określać czy podana odpowiedź w parametrze jest poprawna

2021-06-10 14:25 UTC, FilipProgrammer commented on quiz/quiz.py
> +class Quiz:
jeżeli chodzi o metody question i answer to wyświetlają sformatowane dane pochodzące ze stanu klasy, zobacz jak możesz użyć dekoratora @property w tym przypadku

2021-06-10 14:25 UTC, FilipProgrammer commented on quiz/quiz.py
> +    quiz.question(questions[q_id].qst)
Po zmianach w klasach Quiz i Question ten kod powinien się dosyć mocno uprościć

2021-06-14 13:07 UTC, Kinggred commented
nie ogarniam narazie @property

2021-06-18 10:11 UTC, merged